---
abstract: 'specify a return type for a function (optionally with coercion)'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Return-Type
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Return::Type:
    file: lib/Return/Type.pm
    version: 0.001
requires:
  Eval::TypeTiny: 0
  Scope::Upper: 0
  Sub::Identify: 0
  Sub::Name: 0
  Types::Standard: 0
  Types::TypeTiny: 0
  perl: 5.008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Return-Type/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Return-Type
  homepage: https://metacpan.org/release/Return-Type
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-return-type
version: 0.001
